// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simpleway.proto

package directededge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleWay struct {
	Id                   uint64        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nodes                []*SimpleNode `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	Oneway               string        `protobuf:"bytes,3,opt,name=oneway" json:"oneway,omitempty"`
	Highway              string        `protobuf:"bytes,4,opt,name=highway" json:"highway,omitempty"`
	Junction             string        `protobuf:"bytes,5,opt,name=junction" json:"junction,omitempty"`
	Access               string        `protobuf:"bytes,6,opt,name=access" json:"access,omitempty"`
	MotorVehicle         string        `protobuf:"bytes,7,opt,name=motorVehicle" json:"motorVehicle,omitempty"`
	Service              string        `protobuf:"bytes,8,opt,name=service" json:"service,omitempty"`
	Area                 string        `protobuf:"bytes,9,opt,name=area" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SimpleWay) Reset()         { *m = SimpleWay{} }
func (m *SimpleWay) String() string { return proto.CompactTextString(m) }
func (*SimpleWay) ProtoMessage()    {}
func (*SimpleWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_8fe95426d4d28c48, []int{0}
}
func (m *SimpleWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleWay.Unmarshal(m, b)
}
func (m *SimpleWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleWay.Marshal(b, m, deterministic)
}
func (dst *SimpleWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleWay.Merge(dst, src)
}
func (m *SimpleWay) XXX_Size() int {
	return xxx_messageInfo_SimpleWay.Size(m)
}
func (m *SimpleWay) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleWay.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleWay proto.InternalMessageInfo

func (m *SimpleWay) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleWay) GetNodes() []*SimpleNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *SimpleWay) GetOneway() string {
	if m != nil {
		return m.Oneway
	}
	return ""
}

func (m *SimpleWay) GetHighway() string {
	if m != nil {
		return m.Highway
	}
	return ""
}

func (m *SimpleWay) GetJunction() string {
	if m != nil {
		return m.Junction
	}
	return ""
}

func (m *SimpleWay) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *SimpleWay) GetMotorVehicle() string {
	if m != nil {
		return m.MotorVehicle
	}
	return ""
}

func (m *SimpleWay) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SimpleWay) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

type SimpleNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,3,opt,name=lon" json:"lon,omitempty"`
	Countflag            uint32   `protobuf:"fixed32,4,opt,name=countflag" json:"countflag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleNode) Reset()         { *m = SimpleNode{} }
func (m *SimpleNode) String() string { return proto.CompactTextString(m) }
func (*SimpleNode) ProtoMessage()    {}
func (*SimpleNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_8fe95426d4d28c48, []int{1}
}
func (m *SimpleNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleNode.Unmarshal(m, b)
}
func (m *SimpleNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleNode.Marshal(b, m, deterministic)
}
func (dst *SimpleNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleNode.Merge(dst, src)
}
func (m *SimpleNode) XXX_Size() int {
	return xxx_messageInfo_SimpleNode.Size(m)
}
func (m *SimpleNode) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleNode.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleNode proto.InternalMessageInfo

func (m *SimpleNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleNode) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *SimpleNode) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *SimpleNode) GetCountflag() uint32 {
	if m != nil {
		return m.Countflag
	}
	return 0
}

type WayCollection struct {
	Ways                 []*SimpleWay `protobuf:"bytes,1,rep,name=ways" json:"ways,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WayCollection) Reset()         { *m = WayCollection{} }
func (m *WayCollection) String() string { return proto.CompactTextString(m) }
func (*WayCollection) ProtoMessage()    {}
func (*WayCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_8fe95426d4d28c48, []int{2}
}
func (m *WayCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WayCollection.Unmarshal(m, b)
}
func (m *WayCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WayCollection.Marshal(b, m, deterministic)
}
func (dst *WayCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WayCollection.Merge(dst, src)
}
func (m *WayCollection) XXX_Size() int {
	return xxx_messageInfo_WayCollection.Size(m)
}
func (m *WayCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_WayCollection.DiscardUnknown(m)
}

var xxx_messageInfo_WayCollection proto.InternalMessageInfo

func (m *WayCollection) GetWays() []*SimpleWay {
	if m != nil {
		return m.Ways
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleWay)(nil), "directededge.SimpleWay")
	proto.RegisterType((*SimpleNode)(nil), "directededge.SimpleNode")
	proto.RegisterType((*WayCollection)(nil), "directededge.WayCollection")
}

func init() { proto.RegisterFile("simpleway.proto", fileDescriptor_simpleway_8fe95426d4d28c48) }

var fileDescriptor_simpleway_8fe95426d4d28c48 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0xd2, 0xf4, 0x23, 0x47, 0xf9, 0x90, 0x07, 0x38, 0x21, 0x86, 0x28, 0x53, 0x24, 0xa4,
	0x0c, 0xb0, 0xb2, 0xb1, 0x33, 0x04, 0x89, 0x6e, 0x48, 0xc6, 0x3e, 0x5a, 0xa3, 0xd4, 0x57, 0x25,
	0x29, 0x55, 0x66, 0xfe, 0x38, 0xca, 0xb9, 0x50, 0x10, 0x6c, 0x7e, 0xef, 0xdd, 0xdd, 0xd3, 0x7b,
	0x86, 0xd3, 0xd6, 0xad, 0x37, 0x35, 0xed, 0x74, 0x5f, 0x6e, 0x1a, 0xee, 0x58, 0xcd, 0xad, 0x6b,
	0xc8, 0x74, 0x64, 0xc9, 0x2e, 0x29, 0xff, 0x88, 0x21, 0x7d, 0x94, 0x89, 0x85, 0xee, 0xd5, 0x09,
	0xc4, 0xce, 0x62, 0x94, 0x45, 0x45, 0x52, 0xc5, 0xce, 0xaa, 0x12, 0xc6, 0x9e, 0x2d, 0xb5, 0x18,
	0x67, 0xa3, 0xe2, 0xe8, 0x06, 0xcb, 0x9f, 0xbb, 0x65, 0xd8, 0x7b, 0x60, 0x4b, 0x55, 0x18, 0x53,
	0xe7, 0x30, 0x61, 0x3f, 0x78, 0xe1, 0x28, 0x8b, 0x8a, 0xb4, 0xda, 0x23, 0x85, 0x30, 0x5d, 0xb9,
	0xe5, 0x6a, 0x10, 0x12, 0x11, 0xbe, 0xa0, 0xba, 0x84, 0xd9, 0xdb, 0xd6, 0x9b, 0xce, 0xb1, 0xc7,
	0xb1, 0x48, 0xdf, 0x78, 0xb8, 0xa6, 0x8d, 0xa1, 0xb6, 0xc5, 0x49, 0xb8, 0x16, 0x90, 0xca, 0x61,
	0xbe, 0xe6, 0x8e, 0x9b, 0x27, 0x5a, 0x39, 0x53, 0x13, 0x4e, 0x45, 0xfd, 0xc5, 0x0d, 0x8e, 0x2d,
	0x35, 0xef, 0xce, 0x10, 0xce, 0x82, 0xe3, 0x1e, 0x2a, 0x05, 0x89, 0x6e, 0x48, 0x63, 0x2a, 0xb4,
	0xbc, 0xf3, 0x67, 0x80, 0x43, 0x98, 0x3f, 0x2d, 0x9c, 0xc1, 0xa8, 0xd6, 0x1d, 0xc6, 0x59, 0x54,
	0xc4, 0xd5, 0xf0, 0x14, 0x86, 0xbd, 0x84, 0x1c, 0x18, 0xf6, 0xea, 0x0a, 0x52, 0xc3, 0x5b, 0xdf,
	0xbd, 0xd6, 0x7a, 0x29, 0x19, 0xa7, 0xd5, 0x81, 0xc8, 0xef, 0xe0, 0x78, 0xa1, 0xfb, 0x7b, 0xae,
	0x6b, 0x0a, 0xd1, 0xae, 0x21, 0xd9, 0xe9, 0xbe, 0xc5, 0x48, 0x7a, 0xbd, 0xf8, 0xaf, 0xd7, 0x85,
	0xee, 0x2b, 0x19, 0x7a, 0x99, 0xc8, 0xc7, 0xdd, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x01, 0x36,
	0xb0, 0x87, 0xcb, 0x01, 0x00, 0x00,
}
