// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simpleway.proto

package directededge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SimpleWay struct {
	Id                   uint64        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nodes                []*SimpleNode `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
	Oneway               string        `protobuf:"bytes,3,opt,name=oneway" json:"oneway,omitempty"`
	Highway              string        `protobuf:"bytes,4,opt,name=highway" json:"highway,omitempty"`
	Junction             string        `protobuf:"bytes,5,opt,name=junction" json:"junction,omitempty"`
	Access               string        `protobuf:"bytes,6,opt,name=access" json:"access,omitempty"`
	MotorVehicle         string        `protobuf:"bytes,7,opt,name=motorVehicle" json:"motorVehicle,omitempty"`
	Service              string        `protobuf:"bytes,8,opt,name=service" json:"service,omitempty"`
	Area                 string        `protobuf:"bytes,9,opt,name=area" json:"area,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SimpleWay) Reset()         { *m = SimpleWay{} }
func (m *SimpleWay) String() string { return proto.CompactTextString(m) }
func (*SimpleWay) ProtoMessage()    {}
func (*SimpleWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_30af43a7e180eeb8, []int{0}
}
func (m *SimpleWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleWay.Unmarshal(m, b)
}
func (m *SimpleWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleWay.Marshal(b, m, deterministic)
}
func (dst *SimpleWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleWay.Merge(dst, src)
}
func (m *SimpleWay) XXX_Size() int {
	return xxx_messageInfo_SimpleWay.Size(m)
}
func (m *SimpleWay) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleWay.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleWay proto.InternalMessageInfo

func (m *SimpleWay) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleWay) GetNodes() []*SimpleNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *SimpleWay) GetOneway() string {
	if m != nil {
		return m.Oneway
	}
	return ""
}

func (m *SimpleWay) GetHighway() string {
	if m != nil {
		return m.Highway
	}
	return ""
}

func (m *SimpleWay) GetJunction() string {
	if m != nil {
		return m.Junction
	}
	return ""
}

func (m *SimpleWay) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *SimpleWay) GetMotorVehicle() string {
	if m != nil {
		return m.MotorVehicle
	}
	return ""
}

func (m *SimpleWay) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SimpleWay) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

type SimpleNode struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,3,opt,name=lon" json:"lon,omitempty"`
	Countflag            uint32   `protobuf:"fixed32,4,opt,name=countflag" json:"countflag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleNode) Reset()         { *m = SimpleNode{} }
func (m *SimpleNode) String() string { return proto.CompactTextString(m) }
func (*SimpleNode) ProtoMessage()    {}
func (*SimpleNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_30af43a7e180eeb8, []int{1}
}
func (m *SimpleNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleNode.Unmarshal(m, b)
}
func (m *SimpleNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleNode.Marshal(b, m, deterministic)
}
func (dst *SimpleNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleNode.Merge(dst, src)
}
func (m *SimpleNode) XXX_Size() int {
	return xxx_messageInfo_SimpleNode.Size(m)
}
func (m *SimpleNode) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleNode.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleNode proto.InternalMessageInfo

func (m *SimpleNode) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleNode) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *SimpleNode) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *SimpleNode) GetCountflag() uint32 {
	if m != nil {
		return m.Countflag
	}
	return 0
}

type WayCollection struct {
	Ways                 []*SimpleWay `protobuf:"bytes,1,rep,name=ways" json:"ways,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WayCollection) Reset()         { *m = WayCollection{} }
func (m *WayCollection) String() string { return proto.CompactTextString(m) }
func (*WayCollection) ProtoMessage()    {}
func (*WayCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_30af43a7e180eeb8, []int{2}
}
func (m *WayCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WayCollection.Unmarshal(m, b)
}
func (m *WayCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WayCollection.Marshal(b, m, deterministic)
}
func (dst *WayCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WayCollection.Merge(dst, src)
}
func (m *WayCollection) XXX_Size() int {
	return xxx_messageInfo_WayCollection.Size(m)
}
func (m *WayCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_WayCollection.DiscardUnknown(m)
}

var xxx_messageInfo_WayCollection proto.InternalMessageInfo

func (m *WayCollection) GetWays() []*SimpleWay {
	if m != nil {
		return m.Ways
	}
	return nil
}

type WrittenRoadSegment struct {
	GraphEdgeId          uint64   `protobuf:"varint,1,opt,name=graphEdgeId" json:"graphEdgeId,omitempty"`
	From                 uint64   `protobuf:"varint,2,opt,name=from" json:"from,omitempty"`
	To                   uint64   `protobuf:"varint,3,opt,name=to" json:"to,omitempty"`
	SegmentLengthMm      uint64   `protobuf:"varint,4,opt,name=segmentLengthMm" json:"segmentLengthMm,omitempty"`
	IsAccessOnly         bool     `protobuf:"varint,5,opt,name=isAccessOnly" json:"isAccessOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrittenRoadSegment) Reset()         { *m = WrittenRoadSegment{} }
func (m *WrittenRoadSegment) String() string { return proto.CompactTextString(m) }
func (*WrittenRoadSegment) ProtoMessage()    {}
func (*WrittenRoadSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_30af43a7e180eeb8, []int{3}
}
func (m *WrittenRoadSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrittenRoadSegment.Unmarshal(m, b)
}
func (m *WrittenRoadSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrittenRoadSegment.Marshal(b, m, deterministic)
}
func (dst *WrittenRoadSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrittenRoadSegment.Merge(dst, src)
}
func (m *WrittenRoadSegment) XXX_Size() int {
	return xxx_messageInfo_WrittenRoadSegment.Size(m)
}
func (m *WrittenRoadSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_WrittenRoadSegment.DiscardUnknown(m)
}

var xxx_messageInfo_WrittenRoadSegment proto.InternalMessageInfo

func (m *WrittenRoadSegment) GetGraphEdgeId() uint64 {
	if m != nil {
		return m.GraphEdgeId
	}
	return 0
}

func (m *WrittenRoadSegment) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *WrittenRoadSegment) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *WrittenRoadSegment) GetSegmentLengthMm() uint64 {
	if m != nil {
		return m.SegmentLengthMm
	}
	return 0
}

func (m *WrittenRoadSegment) GetIsAccessOnly() bool {
	if m != nil {
		return m.IsAccessOnly
	}
	return false
}

type OsmWay struct {
	Id                   uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SimpleWay            *SimpleWay            `protobuf:"bytes,2,opt,name=simpleWay" json:"simpleWay,omitempty"`
	ForwardRoadSegments  []*WrittenRoadSegment `protobuf:"bytes,3,rep,name=forwardRoadSegments" json:"forwardRoadSegments,omitempty"`
	BackwardRoadSegments []*WrittenRoadSegment `protobuf:"bytes,4,rep,name=backwardRoadSegments" json:"backwardRoadSegments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OsmWay) Reset()         { *m = OsmWay{} }
func (m *OsmWay) String() string { return proto.CompactTextString(m) }
func (*OsmWay) ProtoMessage()    {}
func (*OsmWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_simpleway_30af43a7e180eeb8, []int{4}
}
func (m *OsmWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsmWay.Unmarshal(m, b)
}
func (m *OsmWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsmWay.Marshal(b, m, deterministic)
}
func (dst *OsmWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsmWay.Merge(dst, src)
}
func (m *OsmWay) XXX_Size() int {
	return xxx_messageInfo_OsmWay.Size(m)
}
func (m *OsmWay) XXX_DiscardUnknown() {
	xxx_messageInfo_OsmWay.DiscardUnknown(m)
}

var xxx_messageInfo_OsmWay proto.InternalMessageInfo

func (m *OsmWay) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OsmWay) GetSimpleWay() *SimpleWay {
	if m != nil {
		return m.SimpleWay
	}
	return nil
}

func (m *OsmWay) GetForwardRoadSegments() []*WrittenRoadSegment {
	if m != nil {
		return m.ForwardRoadSegments
	}
	return nil
}

func (m *OsmWay) GetBackwardRoadSegments() []*WrittenRoadSegment {
	if m != nil {
		return m.BackwardRoadSegments
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleWay)(nil), "directededge.SimpleWay")
	proto.RegisterType((*SimpleNode)(nil), "directededge.SimpleNode")
	proto.RegisterType((*WayCollection)(nil), "directededge.WayCollection")
	proto.RegisterType((*WrittenRoadSegment)(nil), "directededge.WrittenRoadSegment")
	proto.RegisterType((*OsmWay)(nil), "directededge.OsmWay")
}

func init() { proto.RegisterFile("simpleway.proto", fileDescriptor_simpleway_30af43a7e180eeb8) }

var fileDescriptor_simpleway_30af43a7e180eeb8 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x8f, 0xd3, 0x3c,
	0x10, 0x55, 0xd2, 0x6c, 0xdb, 0xcc, 0xee, 0xf7, 0x2d, 0x32, 0x08, 0x2c, 0xc4, 0x21, 0xca, 0x29,
	0x12, 0x52, 0x0f, 0x20, 0x6e, 0x5c, 0x10, 0xe2, 0x80, 0x04, 0xac, 0xe4, 0x45, 0xf4, 0x86, 0xe4,
	0x8d, 0xa7, 0x89, 0x21, 0xb1, 0x2b, 0xdb, 0x4b, 0x95, 0x33, 0x7f, 0x86, 0xbf, 0xc8, 0x0d, 0x79,
	0xb2, 0xa5, 0x2d, 0xad, 0x10, 0xb7, 0x99, 0x37, 0x33, 0x6f, 0xe6, 0x3d, 0x27, 0x70, 0xe9, 0x75,
	0xbf, 0xee, 0x70, 0x23, 0x87, 0xc5, 0xda, 0xd9, 0x60, 0xd9, 0x85, 0xd2, 0x0e, 0xeb, 0x80, 0x0a,
	0x55, 0x83, 0xe5, 0xf7, 0x14, 0xf2, 0x6b, 0xea, 0x58, 0xca, 0x81, 0xfd, 0x0f, 0xa9, 0x56, 0x3c,
	0x29, 0x92, 0x2a, 0x13, 0xa9, 0x56, 0x6c, 0x01, 0x67, 0xc6, 0x2a, 0xf4, 0x3c, 0x2d, 0x26, 0xd5,
	0xf9, 0x33, 0xbe, 0xd8, 0x9f, 0x5d, 0x8c, 0x73, 0x1f, 0xac, 0x42, 0x31, 0xb6, 0xb1, 0x87, 0x30,
	0xb5, 0x26, 0xee, 0xe2, 0x93, 0x22, 0xa9, 0x72, 0x71, 0x97, 0x31, 0x0e, 0xb3, 0x56, 0x37, 0x6d,
	0x2c, 0x64, 0x54, 0xd8, 0xa6, 0xec, 0x31, 0xcc, 0xbf, 0xdc, 0x9a, 0x3a, 0x68, 0x6b, 0xf8, 0x19,
	0x95, 0x7e, 0xe7, 0x91, 0x4d, 0xd6, 0x35, 0x7a, 0xcf, 0xa7, 0x23, 0xdb, 0x98, 0xb1, 0x12, 0x2e,
	0x7a, 0x1b, 0xac, 0xfb, 0x84, 0xad, 0xae, 0x3b, 0xe4, 0x33, 0xaa, 0x1e, 0x60, 0x71, 0xa3, 0x47,
	0xf7, 0x4d, 0xd7, 0xc8, 0xe7, 0xe3, 0xc6, 0xbb, 0x94, 0x31, 0xc8, 0xa4, 0x43, 0xc9, 0x73, 0x82,
	0x29, 0x2e, 0x3f, 0x03, 0xec, 0xc4, 0x1c, 0xb9, 0x70, 0x0f, 0x26, 0x9d, 0x0c, 0x3c, 0x2d, 0x92,
	0x2a, 0x15, 0x31, 0x24, 0xc4, 0x1a, 0x12, 0x19, 0x11, 0x6b, 0xd8, 0x13, 0xc8, 0x6b, 0x7b, 0x6b,
	0xc2, 0xaa, 0x93, 0x0d, 0x69, 0x9c, 0x89, 0x1d, 0x50, 0xbe, 0x84, 0xff, 0x96, 0x72, 0x78, 0x6d,
	0xbb, 0x0e, 0x47, 0x69, 0x4f, 0x21, 0xdb, 0xc8, 0xc1, 0xf3, 0x84, 0x7c, 0x7d, 0x74, 0xca, 0xd7,
	0xa5, 0x1c, 0x04, 0x35, 0x95, 0x3f, 0x12, 0x60, 0x4b, 0xa7, 0x43, 0x40, 0x23, 0xac, 0x54, 0xd7,
	0xd8, 0xf4, 0x68, 0x02, 0x2b, 0xe0, 0xbc, 0x71, 0x72, 0xdd, 0xbe, 0x51, 0x0d, 0xbe, 0xdd, 0xde,
	0xbb, 0x0f, 0x45, 0xa9, 0x2b, 0x67, 0x7b, 0xba, 0x3c, 0x13, 0x14, 0x47, 0x71, 0xc1, 0xd2, 0xe5,
	0x99, 0x48, 0x83, 0x65, 0x15, 0x5c, 0xfa, 0x91, 0xf0, 0x1d, 0x9a, 0x26, 0xb4, 0xef, 0x7b, 0x3a,
	0x3f, 0x13, 0x7f, 0xc2, 0xd1, 0x76, 0xed, 0x5f, 0xd1, 0x13, 0x5c, 0x99, 0x6e, 0xa0, 0xe7, 0x9a,
	0x8b, 0x03, 0xac, 0xfc, 0x99, 0xc0, 0xf4, 0xca, 0xf7, 0xa7, 0xbe, 0xa5, 0x17, 0x90, 0xfb, 0xad,
	0x30, 0xba, 0xe8, 0x2f, 0xba, 0x77, 0x9d, 0x4c, 0xc0, 0xfd, 0x95, 0x75, 0x1b, 0xe9, 0xd4, 0x9e,
	0x76, 0xcf, 0x27, 0x64, 0x5c, 0x71, 0x48, 0x70, 0x6c, 0x92, 0x38, 0x35, 0xcc, 0x3e, 0xc2, 0x83,
	0x1b, 0x59, 0x7f, 0x3d, 0x22, 0xcd, 0xfe, 0x91, 0xf4, 0xe4, 0xf4, 0xcd, 0x94, 0xfe, 0xaf, 0xe7,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x38, 0x18, 0xaf, 0x6e, 0x72, 0x03, 0x00, 0x00,
}
